use_frameworks!

platform :ios, '8.0'

target 'KYProgressHUD_Example' do
  pod 'KYProgressHUD', :path => '../'

  target 'KYProgressHUD_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
