use_frameworks!

platform :ios, '8.0'

target 'KYProgressHUB_Example' do
  pod 'KYProgressHUB', :path => '../'

  target 'KYProgressHUB_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
